version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskfamily"
        LoadBalancerInfo:
          ContainerName: "c1"
          ContainerPort: 80
