version: 0.2

env:
  variables:
    ACCOUNT_ID: "132398229882"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

  post_build:
    commands:
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest

artifacts:
  files:
    - taskdef-${SERVICE_NAME}.json
    - appspec-${SERVICE_NAME}.yaml
  discard-paths: yes
