version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $ECR_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "Build completed on $(date)"

artifacts:
  files:
    - taskdef-app1.json
    - appspec-app1.yaml
  discard-paths: yes
