version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting variables"
      - REGION=$AWS_DEFAULT_REGION
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_NAME=abi

      - echo "Logging in to Amazon ECR in region $REGION"
      - aws ecr get-login-password --region $REGION |
        docker login --username AWS --password-stdin \
        $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest \
        $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo "Pushing image to ECR"
      - docker push \
        $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo "Build completed on $(date)"

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
  discard-paths: yes
