version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      

  post_build:
   commands:
    - docker push $ECR_REPO_URI:$IMAGE_TAG
    - printf '[{"name":"app1","imageUri":"%s"}]' "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - taskdef-app1.json
    - appspec-app1.yaml
