version: 0.2

env:
  variables:
    AWS_REGION: ap-southeast-1
    AWS_ACCOUNT_ID: "132398229882"
    ECR_REPO_NAME: "posistrength-dev-ecr1"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS \
        --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - ECR_REPO_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}

      - echo "ECR_REPO_URI=$ECR_REPO_URI"
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG

      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
